#!/bin/bash

# Attempts to close both portals
# Beware: if the portal symlinks have been moved around, this does not work

source initPortals.sh
source portalUtils.sh

# remove portal files, if they exist
closePortal blue
closePortal orange
