#!/bin/bash

# this script returns a colored string which shows if an 
# open portal is in the current working directory.
#
# Nice to have in the prompt :)
# 
# To add a portal-indicator to your prompt permanently, you have to
# update your ~/.bashrc, for example, you could add following line:
# export PROMPT_COMMAND='export PS1="\[\e]0;\u@\h: \w\a\]\[\033[01;32m\]\u@\h `portalPromptAddon` \[\033[01;34m\]\w \n\[\033[00m\]\$ "'
# 
# This will upgrade your $PS1 (prompt) every time you change the directory.
# After this, you prompt will look like that:
#
# username@host [blue/orange] ~/your/path
# $ your commands
#
# Remember that you have to restart bash or source .bashrc to make the changes visible.
# Just experiment a little bit, adjust it until it suits your needs (I mean the prompt,
# not this script, you can't do much here anyway...)

if [ -L "[blue]" ] 
then
  printf "\[\033[01;36m\][blue]"
else
  if [ -L "[orange]" ]
  then 
    printf "\[\033[01;33m\][orange]"
  fi
fi
